version: 2.1

all_branches_and_version_tag: &all_branches_and_version_tag
  filters:
    tags:
      only: /^\d+[.\d]+.*/

executors:
  docker-executor:
    parameters:
      python_version:
        type: string
        default: "3.11"
    docker:
      - image: cimg/python:<<parameters.python_version>>

jobs:
  test:
    parameters:
      python_version:
        description: "Python Version"
        type: string
    description: Test Python-<<parameters.python_version>>
    executor:
      name: docker-executor
      python_version: "<<parameters.python_version>>"
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install poetry
          command: python -m pip install poetry
      - run:
          name: Install dev tool dependency
          command: python -m poetry install
      - run:
          name: Install backend API dependency
          command: python -m poetry run inv api.init-poetry-env
      - run:
          name: Run tests
          command: python -m poetry run inv api.test

  precommit:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install poetry
          command: python -m pip install poetry
      - run:
          name: Install dev tool dependency
          command: python -m poetry install --with pre-commit
      - run:
          name: Run tests
          command: python -m poetry run inv run-pre-commit

  build-docs:
    description: "Build docs check (the actual publishing is handled by .readthedocs.yaml)"
    executor:
      name: docker-executor
    steps:
      - checkout
      - run:
          name: Install poetry
          command: python -m pip install poetry
      - run:
          name: Install build docs dependency
          command: python -m poetry install --only=docs,dev
      - run:
          name: Run Sphinx
          command: poetry run inv docs.build

workflows:
  tests:
    jobs:
      - test:
          name: test-python<< matrix.python_version >>
          matrix:
            parameters:
              python_version: [ "3.11" ]
          <<: *all_branches_and_version_tag
      - precommit:
          <<: *all_branches_and_version_tag
      - build-docs:
          <<: *all_branches_and_version_tag
